package telegram

const (
	AtlantaHawk            = "/atlantahawk"
	BostonCeltics          = "/bostonceltics"
	BrooklynNets           = "/brooklynnets"
	CharlotteHornets       = "/charlottehornets"
	ChicagoBulls           = "/chicagobulls"
	ClevelandCavaliers     = "/clevelandcavaliers"
	DallasMavericks        = "/dallasmavericks"
	DenverNuggets          = "/denvernuggets"
	DetroitPistons         = "/detroitpistons"
	GoldenStateWarriors    = "/goldenstatewarriors"
	HoustonRockets         = "/houstonrockets"
	IndianaPacers          = "/indianapacers"
	LaClippers             = "/laclippers"
	LosAngelesLakers       = "/losangeleslakers"
	MemphisGrizzlies       = "/memphisgrizzlies"
	MiamiHeat              = "/miamiheat"
	MilwaukeeBucks         = "/milwaukeebucks"
	MinnesotaTimberwolves  = "/minnesotatimberwolves"
	NewOrleansPelicans     = "/neworleanspelicans"
	NewYorkKnicks          = "/newyorkknicks"
	OklahomaCityThunder    = "/oklahomacitythunder"
	OrlandoMagic           = "/orlandomagic"
	Philadelphia76ers      = "/philadelphia76ers"
	PhoenixSuns            = "/phoenixsuns"
	PortlandTrailBlazers   = "/portlandtrailblazers"
	SacramentoKings        = "/sacramentokings"
	SanAntonioSpurs        = "/sanantoniospurs"
	TorontoRaptors         = "/torontoraptors"
	UtahJazz               = "/utahjazz"
	WashingtonWizards      = "/washingtonwizards"
	ChicagoStags           = "/chicagostags"
	StLouisBombers         = "/stlouisbombers"
	ClevelandRebels        = "/clevelandrebels"
	DetroitFalcons         = "/detroitfalcons"
	TorontoHuskies         = "/torontohuskies"
	WashingtonCapitols     = "/washingtoncapitols"
	ProvidenceSteamrollers = "/providencesteamrollers"
	PittsburghIronmen      = "/pittsburghironmen"
	BaltimoreBullets       = "/baltimorebullets"
	IndianapolisJets       = "/indianapolisjets"
	AndersonPackers        = "/andersonpackers"
	WaterlooHawks          = "/waterloohawks"
	IndianapolisOlympians  = "/indianapolisolympians"
	SheboyganRedskins      = "/sheboyganredskins"

	HelpCmd = "/help"
	Start   = "/start"
)
